name: convert design token to css
on: [push]

jobs:
  build_tokens:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      - run: npm install
      - run: npx token-transformer data/tokens.json input/core.json core
      - run: npx token-transformer data/tokens.json input/semantic.json core,semantic core
      # - run: npx token-transformer data/tokens.json input/component.json reference,semantic,component reference,semantic
      - run: npx style-dictionary build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: build tokens
  copy_tokens:
    runs-on: ubuntu-latest
    needs: [build_tokens]
    steps:
      - uses: andstor/copycat-action@v3.2.4
        with:
          personal_token: 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
          src_branch: main
          src_path: build/scss/
          dst_owner: tjyone
          dst_repo_name: sync_demo
          dst_branch: main
          dst_path: src/scss/
          # username: nyan-matt
          # email: matt.rea@gmail.com
          commit_message: copy css tokens        
